### ISSUE TITLE
Requesting my credit for this plugin

### ISSUE THREAD

**Issue by ratchetgame98** [Gamecrafter/HeartMe#2]
Dear Gamecrafter,
I am writing to you as the original author of the plugin ServerLove which this plugin is based on. I require that you credit me for my work on the original code available here https://github.com/ratchetgame98/ServerLove
Since this was my work and I put my own time to code this plugin, I ask politely that you credit me for this and ask for my dearest permission, which I will give to you Free of Charge, before uploading this plugin to the PocketMine forums.
If you don't credit me for my work on the plugin, or ask for my permission to upload the plugin, the GitHub repository and the plugin will be taken down from any further commits or downloads.
Also, I only gave you permission to re-write the original source code into PHP, not to change it in any way, shape or form, or change the name of the original plugin. I ask you to keep the original code as it was and only to port it over to PHP, not to change any of the code to your own preferences or to change the original name of the plugin
I politely ask that you keep the source code as it was written, and only to make it available for PcketMine. If these changes aren't made, I will be forced to take down this plugin and revoke any permission given to you from myself to make the plugin available on PocketMine.

Yours Sincerely
ratchetgame98
Original ServerLove Coder

**Comment by Gamecrafter** [comment]
Sorry to tell you, but I do not need your permission to release the plugin. This is a free world. I have not looked at the code for ServerLove, and I will not. Clearly, the plugin I am writing will be from scratch. I will credit you for the original idea. I never said I would port your ServerLove plugin, only make one that did what a dating plugin would do, for PocketMine-MP, period.
